{"uuid": "85e99e8a-e753-45ea-946b-54f3213e98c9", "children": ["5386d0c5-32f5-4e0d-b704-b6ca1413077c"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: Requested environment is not available\n\n", "trace": "  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/tests/conftest.py\", line 23, in setup_browser\n    driver = webdriver.Remote(\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/home/eli/PycharmProjects/qa_guru_8_12_homework/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698477851825, "stop": 1698477852364}], "start": 1698477851825, "stop": 1698477852533}